version: "3.8"
services:
  back:
    image: my-bank/back
    build: 
      context: ./back
      dockerfile: Dockerfile.dev
    ports:
      - $BACK_PORT:8080
    environment:
      NODE_ENV: development
      PASSWORD_SALT: $BACK_PASSWORD_SALT
      SALT_ROUNDS: $BACK_SALT_ROUNDS
      JWT_SECRET: $BACK_JWT_SECRET
      JWT_TOKEN_EXP_IN_MINUTES: $BACK_JWT_TOKEN_EXP_IN_MINUTES
      FRONT_PORT: $FRONT_PORT
      DB_HOST: db
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
    volumes:
      - ./back/src/:/usr/src/back/src/
    depends_on:
      - db
    
  front:
    image: my-bank/front
    build: 
      context: ./front
      dockerfile: Dockerfile.dev
    ports:
      - $FRONT_PORT:3000
    environment:
      REACT_APP_BACK_PORT: $BACK_PORT
    volumes:
      - ./front/src/:/usr/src/front/src/
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/1.sql
      - ./db/dev:/var/lib/mysql
